version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: forumdb
      MYSQL_USER: forumuser
      MYSQL_PASSWORD: forumpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://forumuser:forumpass@db:3306/forumdb"
    volumes:
      - .:/app

volumes:
  mysql_data:
